name: Build Android App
on:
  workflow_dispatch:
jobs:
  Build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Checking release version
        id: version
        run: |
          echo ::set-output name=release_version::$(cat app/build.gradle  | grep -o "versionName \"[0-9.]*\"" | grep -o "[0-9.]*")
          echo ::set-output name=release_patch::$(git rev-parse --short HEAD)
      - name: Update version
        run: |
          sed -i "s/versionCode .*/versionCode $(date +%Y%m%d)/" ./app/build.gradle
          sed -i "s/versionName .*/versionName \"${{ steps.version.outputs.release_version }}-${{ steps.version.outputs.release_patch }}\"/" ./app/build.gradle
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew --no-daemon --no-configuration-cache -q app:assembleRelease
      - name: Rename APK
        run: |
          APK="BFR_Manager_v${{ steps.version.outputs.release_version }}_${{ steps.version.outputs.release_patch }}.apk"
          mv -f ./app/build/outputs/apk/release/*.apk ./app/build/outputs/apk/release/$APK
      - name: Delete tag if exists
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          delete_release: true
          tag_name: "v${{ steps.version.outputs.release_version }}_${{ steps.version.outputs.release_patch }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag Release
        uses: richardsimko/update-tag@v1.0.11
        with:
          tag_name: "v${{ steps.version.outputs.release_version }}_${{ steps.version.outputs.release_patch }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: "v${{ steps.version.outputs.release_version }}_${{ steps.version.outputs.release_patch }}"
          files: ${{ github.workspace }}/app/build/outputs/apk/release/*.apk
          draft: false
          generate_release_notes: true
